/*
vagrant ssh master
sudo apt-get update
wget -qO- https://get.docker.com/ | sh
sudo usermod -aG docker vagrant 
exit
vagrant ssh master
*/

FROM ubuntu:14.04

RUN sudo apt-get update -y
RUN sudo apt-get install -y wget
RUN sudo apt-get install -y tar
RUN sudo apt-get install -y openssh-server openssh-client
RUN sudo apt-get install -y puppet puppetmaster
RUN sudo ufw disable
RUN sudo sed -i -e '2i10.50.15.184 Master.netbuilder.private puppetmaster' /etc/hosts
RUN sudo sed -i -e '2i127.0.0.1 Master.netbuilder.private' /etc/hosts
RUN sudo touch /etc/puppet/autosign.conf
RUN sudo echo 'Agent.netbuilder.private' >> /etc/puppet/autosign.conf
RUN sudo touch /etc/puppet/manifests/site.pp


/*
WORKDIR /opt
RUN sudo wget http://10.50.20.21:8080/aaron/downloads/jdk-8u45-linux-x64.tar.gz
RUN sudo pwd
RUN sudo ls -a
RUN sudo tar zxvf jdk-8u45-linux-x64.tar.gz
RUN JAVA_HOME=/opt/jdk1.8.0_45 &&\
    export JAVA_HOME && \
    PATH=$PATH:$PATH:$JAVA_HOME/bin && \
    JRE_HOME=/opt/jdk1.8.0_45/jre && \
    export JRE_HOME && \
    PATH=$PATH:$PATH:JRE_HOME/bin
RUN sudo update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_45/bin/java 1
RUN sudo update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_45/bin/javac 1
RUN java -version

WORKDIR /opt
RUN sudo wget http://http://10.50.20.21:8080/aaron/downloads/apache-maven-3.3.3-bin.tar.gz
RUN sudo pwd
RUN sudo ls -a
RUN sudo tar zxvf apache-maven-3.3.3-bin.tar.gz
RUN export MAVEN_HOME=/opt/apache-maven-3.3.3/bin && \
    export M2=$MAVEN_HOME/bin && \
    export PATH=$M2/bin:$PATH
RUN sudo update-alternatives --install /usr/bin/mvn mvn /opt/apache-maven-3.3.3/bin/mvn 2
RUN mvn -version

WORKDIR /opt
RUN sudo apt-get install -y libcurl4-gnutls-dev libexpat1-dev gettext \libz-dev libssl-dev
RUN sudo wget -nv http://10.50.20.21:8080/aaron/downloads/git-2.5.0.tar.gz -O git-2.5.0.tar.gz
RUN sudo ls -a
RUN sudo tar zxvf git-2.5.0.tar.gz
WORKDIR /opt/git-2.5.0
RUN sudo make prefix=/usr/local all
RUN sudo make prefix=/usr/local install
*/