
FROM ubuntu:14.04

RUN sudo apt-get update -y
RUN sudo apt-get install -y wget
RUN sudo apt-get install -y tar
RUN sudo apt-get install -y openssh-server openssh-client
RUN sudo apt-get install -y puppet puppetmaster
RUN sudo ufw disable
RUN sudo sed -i -e '2i10.50.15.184 Master.netbuilder.private puppetmaster' /etc/hosts
RUN sudo sed -i -e '2i127.0.0.1 Master.netbuilder.private' /etc/hosts
RUN sudo touch /etc/puppet/autosign.conf
RUN sudo echo 'Agent.netbuilder.private' >> /etc/puppet/autosign.conf
RUN sudo touch /etc/puppet/manifests/site.pp
